// Code generated by "stringer -type=DocumentType -trimprefix=DocumentType"; DO NOT EDIT.

package digiposte

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DocumentTypeBasic-0]
	_ = x[DocumentTypeHealth-1]
}

const _DocumentType_name = "BasicHealth"

var _DocumentType_index = [...]uint8{0, 5, 11}

func (i DocumentType) String() string {
	if i < 0 || i >= DocumentType(len(_DocumentType_index)-1) {
		return "DocumentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DocumentType_name[_DocumentType_index[i]:_DocumentType_index[i+1]]
}
