// Code generated by "stringer -type=Location -linecomment"; DO NOT EDIT.

package digiposte

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LocationInbox-0]
	_ = x[LocationSafe-1]
	_ = x[LocationTrashInbox-2]
	_ = x[LocationTrashSafe-3]
}

const _Location_name = "INBOXSAFETRASH_INBOXTRASH_SAFE"

var _Location_index = [...]uint8{0, 5, 9, 20, 30}

func (i Location) String() string {
	if i < 0 || i >= Location(len(_Location_index)-1) {
		return "Location(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Location_name[_Location_index[i]:_Location_index[i+1]]
}
