// Code generated by "stringer -type=ProfileMode -linecomment"; DO NOT EDIT.

package digiposte

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProfileModeDefault-0]
	_ = x[ProfileModeNoSpaceConsumption-1]
}

const _ProfileMode_name = "defaultwithout_space_consumption"

var _ProfileMode_index = [...]uint8{0, 7, 32}

func (i ProfileMode) String() string {
	if i < 0 || i >= ProfileMode(len(_ProfileMode_index)-1) {
		return "ProfileMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProfileMode_name[_ProfileMode_index[i]:_ProfileMode_index[i+1]]
}
