version: "2"
linters:
  default: all
  disable:
    - tagliatelle
  settings:
    depguard:
      rules:
        login:
          list-mode: lax
          files:
            - login/**.go
          allow:
            - $gostd
            - github.com/chromedp
            - github.com/holyhope
            - github.com/Davincible/chromedp-undetected
            - github.com/go-oauth2/oauth2/v4
            - github.com/pquerna/otp
            - github.com/go-rod/rod/lib/launcher
        tests:
          list-mode: lax
          files:
            - $test
          allow:
            - $gostd
            - github.com/holyhope
            - github.com/onsi/ginkgo
            - github.com/onsi/gomega
            - github.com/go-rod/rod/lib/launcher
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - nosnakecase
        path: _example_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - dot
        - default
        - prefix(github.com/holyhope/digiposte-go-sdk)
        - blank
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
